config/routes.rb
ProcessAllocx::Engine.routes.draw do

  resources :allocations
  root :to => 'allocations#index'
end

app/models/process_allocx/allocation.rb
module ProcessAllocx
  class Allocation < ActiveRecord::Base
    attr_accessor :active_noupdate, :last_updated_by_name, :operator_name, :equipment_name, :process_name, :status_name
    attr_accessible :active, :allocation_category, :brief_note, :description, :end_date, :equipment_id, :operator_id, :process_id, :qty_in, 
                    :qty_out, :start_date, :status_id, :process_name,
                    :as => :role_new
    attr_accessible :active, :allocation_category, :brief_note, :description, :end_date, :equipment_id, :operator_id, :process_id, :qty_in, 
                    :qty_out, :start_date, :status_id, 
                    :active_noupdate, :last_updated_by_name, :operator_name, :equipment_name, :process_name, :status_name,
                    :as => :role_update
    
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :equipment, :class_name => ProcessAllocx.equipment_class.to_s
    belongs_to :operator, :class_name => 'Authentify::User'
    belongs_to :process, :class_name => ProcessAllocx.process_class.to_s
    belongs_to :status, :class_name => 'Commonx::MiscDefinition'

    validates :allocation_category, :presence => true
    validates :process_id, :equipment_id, :operator_id, :presence => true, :numericality => {:only_integer => true, :greater_than => 0}
    validates :qty_in, :presence => true, :numericality => {:only_integer => true, :greater_than_or_equal_to => 0}, :if => 'qty_in.present?'
    validates :qty_out, :presence => true, :numericality => {:only_integer => true, :greater_than_or_equal_to => 0}, :if => 'qty_out.present?'
    validates :qty_out, :numericality => {:less_than_or_equal_to => :qty_in, :message => I18n.t('Wrong Qty Out')}, :if => 'qty_out.present?'
    validate :dynamic_validate
      
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'process_allocx')
      eval(wf) if wf.present?
    end
  end
end

app/controllers/process_allocx/allocations_controller.rb
require_dependency "process_allocx/application_controller"

module ProcessAllocx
  class AllocationsController < ApplicationController
    before_filter :require_employee
    before_filter :init_resource


    def index
      @title = t('Resource Allocations')
      @allocations = params[:process_allocx_allocations][:model_ar_r]
      @allocations = @allocations.where('process_allocx_allocations.process_id = ?', @process.id) if @process
      @allocations = @allocations.where('TRIM(process_allocx_allocations.allocation_category) = ?', @allocation_category) if @allocation_category
      @allocations = @allocations.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('allocation_index_view_' + @allocation_category, 'process_allocx')
    end

    def new
      @title = t('New Allocation')
      @allocation = ProcessAllocx::Allocation.new()
      session[:allocation_category] = @allocation_category
      @erb_code = find_config_const('allocation_new_view_' + @allocation_category, 'process_allocx')
    end

    def create
      @allocation = ProcessAllocx::Allocation.new(params[:allocation], :as => :role_new)
      @allocation.last_updated_by_id = session[:user_id]
      @allocation_category = session[:allocation_category]
      @allocation.allocation_category = @allocation_category
      if @allocation.save
        session[:allocation_category] = nil
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @process = ProcessAllocx.process_class.find_by_id(params[:allocation][:process_id].to_i) if params[:allocation][:process_id].present?
        @erb_code = find_config_const('allocation_new_view_' + @allocation.allocation_category, 'process_allocx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end

    def edit
      @title = t('Edit Allocation')
      @allocation = ProcessAllocx::Allocation.find(params[:id])
      @erb_code = find_config_const('allocation_edit_view_' + @allocation.allocation_category, 'process_allocx')
    end

    def update
      @allocation = ProcessAllocx::Allocation.find(params[:id])
      @allocation.last_updated_by_id = session[:user_id]
      if @allocation.update_attributes(params[:allocation], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('allocation_edit_view_' + @allocation.allocation_category, 'process_allocx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'edit'
      end

    end

    def show
      @title = t('Allocation Info')
      @allocation = ProcessAllocx::Allocation.find(params[:id])
      @erb_code = find_config_const('allocation_show_view_' + @allocation.allocation_category, 'process_allocx')
    end

    protected
    
    def init_resource
      @process = ProcessAllocx.process_class.find_by_id(ProcessAllocx::Allocation.find_by_id(params[:id]).process_id) if params[:id].present?   
      @process = ProcessAllocx.process_class.find_by_id(params[:process_id].to_i) if params[:process_id].present?
      @allocation_category = ProcessAllocx::Allocation.find_by_id(params[:id]).allocation_category if params[:id].present? 
      @allocation_category = params[:allocation_category].strip if params[:allocation_category].present?
    end

  end
end

app/controllers/process_allocx/application_controller.rb
module ProcessAllocx
  class ApplicationController < ApplicationController

    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_filter :require_signin
    before_filter :max_pagination
    before_filter :check_access_right 
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]  #for parent_record_id & parent_resource in check_access_right
    before_filter :view_in_config?
   
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination').to_i
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/helpers/process_allocx/allocations_helper.rb
module ProcessAllocx
  module AllocationsHelper
  end
end

app/helpers/process_allocx/application_helper.rb
module ProcessAllocx
  module ApplicationHelper
  end
end

app/views/process_allocx/allocations/_form.html.erb
<% if @view_in_config && @erb_code %>
    <%= render inline: @erb_code %>
<% else %>
<%= simple_form_for @allocation do |f| %>    
	  <%= f.input :process_name, :label => t('Process'), :input_html => {:value => @process.batch_status.name} %>
      <%= f.input :operator_id, :label => t('Operator'), :collection => Authentify::UsersHelper.return_users('index', 'process_allocx_allocations'), :include_blank => true %>
      <%= f.input :equipment_id, :label => t('Equipment'), :collection => ProcessAllocx.equipment_class.where(decommissioned: false).order('name'), :include_blank => true %>
      <%= f.input :description, :label => t('Description'), :input_html => {:rows => 1} %>
      <%= f.input :qty_in, :label => t('Qty In') %>
      <%= f.input :qty_out, :label => t('Qty Out') %>   
	  <% if readonly?(@allocation, 'active')%>
	    <%= f.input :active_noupdate, :label => t('Active'), :input_html => {:value => (@allocation.active ? t('Yes') : t('No'))} %>
	  <% else %>
	    <%= f.input :active, :label => t('Active'), :collection => [[t('Yes'), true], [t('No'), false]], :include_blank => true %>
	  <% end %>
	  <%= f.input :last_updated_by_name, :label => t('Last Updated By'), :readonly => true, :input_html => {:value => @allocation.last_updated_by.name} %>
      
      <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
	  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/process_allocx/allocations/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div class="pagination"><%= will_paginate models %></div>
    <table class="table table-striped">
		<tr>
            <th>#</th>
			<th><%= t('Process Name') %></th>
			<th><%= t('Description') %></th>
			<th><%= t('Operator') %></th>
			<th><%= t('Equipment') %></th>
			<th><%= t('Qty In') %></th>
			<th><%= t('Qty Out') %></th>
			<th><%= t('Last updated by') %></th>
			<th></th>
		</tr>
		<% models.each do |r| %>
		  <tr>
            <% if has_action_right?('show', 'process_allocx_allocations', r) %>
                <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{allocation_path(r)}"  %></td>
            <% else %>
                <td><%= r.id %></td>
            <% end %>
		  	<td><%= @process.batch_status.name %></td>
		  	<td><%= prt(r, :description)  %></td>
		  	<td><%= prt(r, 'operator.name') %></td>
			<td><%= prt(r, 'equipment.name') %></td>
			<td><%= prt(r, :qty_in)  %></td>
			<td><%= prt(r, :qty_out) %></td>
			<td><%= prt(r, 'last_updated_by.name') %></td>    
		    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_allocation_path(r)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
		    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_allocation_path(r, :subaction => @allocation_category)}", :class => BUTTONS_CLS['action']  if has_action_right?('update_' + @allocation_category, params[:controller], r) %></td>
		  </tr>
		<% end %>
	</table>
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to t('New Allocation'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape new_allocation_path(process_id: @process.id, allocation_category: @allocation_category)}", :class => BUTTONS_CLS['action'] if @allocation_category && @process && has_action_right?('create', params[:controller]) %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to t('New Allocation'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape new_allocation_path(process_id: @process.id, allocation_category: @allocation__category, subaction: @allocation_category)}", :class => BUTTONS_CLS['action'] if @allocation_category && @process && has_action_right?('create_' + @allocation_category, params[:controller]) %>
	  
	    </th>
	  </tr>
	</table>
	
<% end %>

app/views/process_allocx/allocations/_form_new.html.erb
<% if @view_in_config && @erb_code %>
    <%= render inline: @erb_code %>
<% else %>
  <%= simple_form_for @allocation do |f| %>
    <%= f.input :process_name, :label => t('Process'), :readonly => true, :input_html => {:value => @process.batch_status.name} %>
    <%= f.input :process_id, :as => :hidden, :input_html => {:value => @process.id} %>
    <%= f.input :operator_id, :label => t('Operator'), :collection => Authentify::UsersHelper.return_users('index', 'process_allocx_allocations'), :include_blank => true %>
    <%= f.input :equipment_id, :label => t('Equipment'), :collection => ProcessAllocx.equipment_class.where(decommissioned: false).order('name'), :include_blank => true %>
    <%= f.input :description, :label => t('Description'), :input_html => {:rows => 1} %>
    <%= f.input :qty_in, :label => t('Qty In') %>
    <%= f.input :qty_out, :label => t('Qty Out') %>
    
    
    <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
    <%= f.button :submit, t('Save') , :class => BUTTONS_CLS['action'] %>
  <% end %>

<% end %>

app/views/process_allocx/allocations/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/task_definitions/create.html.erb</p>

app/views/process_allocx/allocations/edit.html.erb
<div id="main_body">
<h4><%=@title %></h4>

	<%= render 'form' %>

</div>
  
 

app/views/process_allocx/allocations/index.html.erb
<div id="main_body">
	<h4><%= @title %>-<%=t(@allocation_category)%></h4>	
		<%= render partial: 'form_list', locals: {models: @allocations} %>	
</div>

app/views/process_allocx/allocations/new.html.erb
<div id="main_body">
  <h4><%= @title %></h4>

  <%= render 'form_new' %>

</div>

app/views/process_allocx/allocations/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div id="main_body">
<h4><%=@title %></h4>

<p>
  <b><%= t('Description') %></b>
  <%= @allocation.description %>
</p>
<p>
  <b><%=t('Operator')%>:</b>
  <%= Authentify::User.find_by_id(@allocation.operator_id).name %>
</p>
<p>
  <b><%=t('Equipment')%>:</b>
  <%= ProcessAllocx.equipment_class.find_by_id(@allocation.equipment_id).name %>
</p>
<p>
  <b><%= t('Qty In') %></b>
  <%= @allocation.qty_in %>
</p>
<p>
  <b><%= t('Qty Out') %></b>
  <%= @allocation.qty_out %>
</p>
<p>
  <b><%= t('Active') %></b>
  <%= @allocation.active ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @allocation.last_updated_by.name if @allocation.last_updated_by_id.present? %>
</p>


  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
  
</div>

<% end %>

app/views/process_allocx/allocations/update.html.erb
<h1>EventTasks#update</h1>
<p>Find me in app/views/event_taskx/event_tasks/update.html.erb</p>